workflows:
  ios-build-for-sibapp:
    name: Build unsigned iOS IPA for SibApp
    environment:
      xcode: latest
    scripts:
      - name: Confirm libiPhone-lib.a exists and is real
        script: |
          echo "🔍 Checking if libiPhone-lib.a exists..."
          if [ ! -f Libraries/libiPhone-lib.a ]; then
            echo "❌ libiPhone-lib.a NOT FOUND in Codemagic build environment!"
            echo "🚫 Build cancelled. Make sure the file is committed correctly and not blocked by Git LFS."
            exit 1
          fi
          echo "✅ libiPhone-lib.a exists!"
          echo "📏 File size:"
          du -h Libraries/libiPhone-lib.a

      - name: Build Xcode project without signing
        script: |
          echo "🚧 Archiving project..."
          xcodebuild \
            -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -archivePath build/Unity.xcarchive \
            archive CODE_SIGNING_ALLOWED=NO

          echo "📦 Exporting .ipa..."
          xcodebuild \
            -exportArchive \
            -archivePath build/Unity.xcarchive \
            -exportPath build/export \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/export/*.ipa
